apiVersion: v2
name: datahub-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.10
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  # This chart deploys an enterprise version of neo4j that requires commercial license
  - name: mysql
    version: 9.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: postgresql
    version: 11.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  # This chart deploys an enterprise version of kafka that requires commercial license
  # Note, Schema registry and kafka rest proxy do not require the commercial license
  - name: cp-helm-charts
    version: 0.6.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled
  # This chart deploys a community version of kafka
  - name: kafka
    version: 17.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io
